name: Build LaTeX document

# on: [push]
on:
  workflow_dispatch:
    inputs:
      exercise_class_nr:
        description: 'which exercise class slides should be generated?'
        type: string
        required: true
        default: 1

jobs:
  build_for_juergen:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - uses: xu-cheng/texlive-action/full@v1
      with:
        run: |
          apk add make
          cd 'Tutorat${{ github.event.inputs.exercise_class_nr }}'
          make 'Tutorat${{ github.event.inputs.exercise_class_nr }}.pdf'
      continue-on-error: true
    - name: Push log file
      uses: dmnemec/copy_file_to_another_repo_action@main
      env:
        API_TOKEN_GITHUB: ${{ secrets.UPLOAD_TO_REPO }}
      with:
        source_file: 'Tutorat1/Tutorat${{ github.event.inputs.exercise_class_nr }}.log'
        destination_repo: 'matthejue/Einfuehrung_in_ESE_Tutoratsfolien_out'
        destination_folder: ''
        destination_branch: 'main'
        user_email: 'matthejue@gmail.com'
        user_name: 'matthejue'
        commit_message: 'updated log for Juergen'
    - name: Push test file
      uses: dmnemec/copy_file_to_another_repo_action@main
      env:
        API_TOKEN_GITHUB: ${{ secrets.UPLOAD_TO_REPO }}
      with:
        source_file: 'Tutorat1/Tutorat${{ github.event.inputs.exercise_class_nr }}.pdf'
        destination_repo: 'matthejue/Einfuehrung_in_ESE_Tutoratsfolien_out'
        destination_folder: ''
        destination_branch: 'main'
        user_email: 'matthejue@gmail.com'
        user_name: 'matthejue'
        commit_message: 'updated pdf for Juergen'

  # # Pascal
  build_for_pascal:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - uses: xu-cheng/texlive-action/full@v1
      with:
        run: |
          apk add make
          cd 'Tutorat${{ github.event.inputs.exercise_class_nr }}'
          cp 'Tutorat${{ github.event.inputs.exercise_class_nr }}.tex' 'Tutorat${{ github.event.inputs.exercise_class_nr }}a.tex'
          sed -i "s/\\\def\\\pascal{0}/\\\def\\\pascal{1}/" 'Tutorat${{ github.event.inputs.exercise_class_nr }}a.tex'
          make 'Tutorat${{ github.event.inputs.exercise_class_nr }}a.pdf'
      continue-on-error: true
    - name: Push log file
      uses: dmnemec/copy_file_to_another_repo_action@main
      env:
        API_TOKEN_GITHUB: ${{ secrets.UPLOAD_TO_REPO }}
      with:
        source_file: 'Tutorat1/Tutorat${{ github.event.inputs.exercise_class_nr }}a.log'
        destination_repo: 'matthejue/Einfuehrung_in_ESE_Tutoratsfolien_out'
        destination_folder: ''
        destination_branch: 'main'
        user_email: 'matthejue@gmail.com'
        user_name: 'matthejue'
        commit_message: 'updated log for Pascal'
    - name: Push test file
      uses: dmnemec/copy_file_to_another_repo_action@main
      env:
        API_TOKEN_GITHUB: ${{ secrets.UPLOAD_TO_REPO }}
      with:
        source_file: 'Tutorat1/Tutorat${{ github.event.inputs.exercise_class_nr }}a.pdf'
        destination_repo: 'matthejue/Einfuehrung_in_ESE_Tutoratsfolien_out'
        destination_folder: ''
        destination_branch: 'main'
        user_email: 'matthejue@gmail.com'
        user_name: 'matthejue'
        commit_message: 'updated pdf for Pascal'
